# Generated by Django 4.1.4 on 2023-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_asset_image_alter_asset_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.FileField(default='images/asset.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('in use', 'In Use'), ('in repair', 'In Repair'), ('deleted', 'Deleted')], default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
