# Generated by Django 4.1.4 on 2023-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_asset_image_alter_asset_status_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(default='images/asset.jpeg', upload_to='images/'),
        ),
    ]
