# Generated by Django 4.1.4 on 2023-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.FileField(default='images/asset.jpeg', upload_to='images/'),
        ),
    ]
